import { getDb } from './client';
import { getSelection } from './evidence';
import { proposalData } from './proposal';
export async function getComparison(threshold:number){
 const [selection,latency]=await Promise.all([getSelection(),getDb().$client.prepare(`SELECT s.seed_key AS site,l.value AS latency,d.value AS share FROM current_metrics l JOIN sites s ON s.id=l.site_id JOIN current_metrics d ON d.demand_region_id=l.demand_region_id AND d.metric_name='demand_share' WHERE l.metric_name='round_trip_latency'`).all<{site:string;latency:number|null;share:number}>()]);
 const criteria=proposalData.criteria.map(c=>({...c,name:selection.criteria.find(x=>x.code===c.id)?.name??c.name,weight:selection.weights.find(x=>x.criterion_code===c.id)?.weight??c.weight}));
 const candidates=proposalData.candidates.map(c=>{const rows=latency.results.filter(r=>r.site===c.id);const share=rows.length?rows.filter(r=>r.latency!==null&&r.latency<=threshold).reduce((sum,r)=>sum+r.share,0):c.demandShare;const proximityScore=share>=60?5:share>=45?4:share>=30?3:share>=15?2:1;const scores=criteria.map((criterion,j)=>criterion.id==='K10'?proximityScore:selection.assessments.find(a=>a.site_key===c.id&&a.criterion_code===criterion.id)?.score??c.scores[j]);return {...c,scores,demandShare:Math.round(share*10)/10,meanRtt:rows.length?rows.filter(r=>r.latency!==null).reduce((sum,r)=>sum+r.latency!*r.share/100,0):null,score:criteria.reduce((sum,k,j)=>sum+scores[j]*k.weight/100,0)};});
 return {criteria,candidates,gates:selection.assessments.filter(a=>a.gate_result)};
}
export async function getComparisonMetrics(){return (await getDb().$client.prepare(`SELECT m.metric_name,m.value,m.unit,m.reporting_period,m.retrieved_at,m.notes,m.claim_type,c.seed_key AS country,s.seed_key AS site,src.url,src.publisher FROM current_metrics m LEFT JOIN countries c ON c.id=m.country_id LEFT JOIN sites s ON s.id=m.site_id JOIN sources src ON src.id=m.source_id WHERE m.demand_region_id IS NULL ORDER BY m.metric_name`).all<{metric_name:string;value:number|null;unit:string;reporting_period:string;retrieved_at:string;notes:string;claim_type:string;country:string|null;site:string|null;url:string;publisher:string}>()).results;}
