import { getDb } from './client';
export type SourceRecord={id:number;seed_key:string|null;publisher:string;title:string;url:string;publication_date:string|null;accessed_at:string;excerpt:string|null;notes:string|null};
export type MetricRecord={id:number;seed_key:string|null;metric_name:string;value:number|null;unit:string;reporting_period:string;retrieved_at:string;confidence:string;claim_type:string;notes:string|null;source_id:number;publisher:string;url:string;title:string};
export type ClaimRecord={id:number;seed_key:string|null;design_id:number;claim_text:string;claim_type:string;value:number|null;unit:string|null;calc_key:string|null;topic:string;created_at:string;confidence:string|null;source_id:number|null};
const db=()=>getDb().$client;
export async function getCountries(){return (await db().prepare('SELECT id,seed_key,name,region FROM countries ORDER BY id').all<{id:number;seed_key:string;name:string;region:string}>()).results;}
export async function getSites(){return (await db().prepare('SELECT s.*,c.name AS country FROM sites s JOIN countries c ON c.id=s.country_id ORDER BY s.id').all()).results;}
export async function getCountryMetrics(countryId:number,names?:string[]){const rows=(await db().prepare('SELECT m.*,s.publisher,s.title,s.url FROM current_metrics m JOIN sources s ON s.id=m.source_id WHERE m.country_id=? ORDER BY m.metric_name').bind(countryId).all<MetricRecord>()).results;return names?.length?rows.filter(r=>names.includes(r.metric_name)):rows;}
export async function getSiteMetrics(siteId:number,names?:string[]){const rows=(await db().prepare('SELECT m.*,s.publisher,s.title,s.url FROM current_metrics m JOIN sources s ON s.id=m.source_id WHERE m.site_id=? ORDER BY m.metric_name').bind(siteId).all<MetricRecord>()).results;return names?.length?rows.filter(r=>names.includes(r.metric_name)):rows;}
export async function getDesign(teamId:number){const design=await db().prepare('SELECT d.*,s.name AS site,c.name AS country FROM designs d LEFT JOIN sites s ON s.id=d.selected_site_id LEFT JOIN countries c ON c.id=d.selected_country_id WHERE d.team_id=?').bind(teamId).first<{id:number;team_id:number;name:string;design_summary:string;site:string;country:string}>();if(!design)return null;const parameters=(await db().prepare('SELECT p.name,p.value,p.rationale,p.created_at,u.unit FROM current_parameters p JOIN parameter_definitions u ON u.name=p.name WHERE p.design_id=?').bind(design.id).all<{name:string;value:number;rationale:string;created_at:string;unit:string}>()).results;return {...design,parameters};}
export async function getPublicDesign(){const team=await db().prepare('SELECT id FROM teams WHERE seed_key=?').bind('university-demo-team').first<{id:number}>();return team?getDesign(team.id):null;}
export async function getDesignClaims(designId:number,types?:string[]){const claims=(await db().prepare('SELECT * FROM current_claims WHERE design_id=? ORDER BY id').bind(designId).all<ClaimRecord>()).results;return types?.length?claims.filter(c=>types.includes(c.claim_type)):claims;}
export async function getSources(){return (await db().prepare('SELECT id,seed_key,publisher,title,url,publication_date,accessed_at,excerpt,notes FROM current_sources ORDER BY id').all<SourceRecord>()).results;}
export async function getClaimSourceMap(designId:number){const rows=(await db().prepare(`WITH RECURSIVE tree(root,id) AS (SELECT id,id FROM current_claims WHERE design_id=? UNION SELECT t.root,l.input_claim_id FROM tree t JOIN claim_links l ON l.claim_id=t.id WHERE l.input_claim_id IS NOT NULL) SELECT DISTINCT t.root,s.id AS source_id FROM tree t JOIN design_claims c ON c.id=t.id LEFT JOIN claim_links l ON l.claim_id=t.id LEFT JOIN metrics m ON m.id=l.metric_id JOIN sources s ON s.id=c.source_id OR s.id=l.source_id OR s.id=m.source_id`).bind(designId).all<{root:number;source_id:number}>()).results;const map:Record<number,number[]>={};for(const r of rows)(map[r.root]??=[]).push(r.source_id);return map;}
export async function getClaimEvidence(claimId:number){
  const claims=(await db().prepare(`WITH RECURSIVE tree(id) AS (SELECT ? UNION SELECT l.input_claim_id FROM claim_links l JOIN tree t ON t.id=l.claim_id WHERE l.input_claim_id IS NOT NULL) SELECT c.* FROM design_claims c JOIN tree t ON t.id=c.id`).bind(claimId).all<ClaimRecord>()).results;
  const sources=(await db().prepare(`WITH RECURSIVE tree(id) AS (SELECT ? UNION SELECT l.input_claim_id FROM claim_links l JOIN tree t ON t.id=l.claim_id WHERE l.input_claim_id IS NOT NULL) SELECT DISTINCT s.* FROM sources s WHERE s.id IN (SELECT l.source_id FROM claim_links l JOIN tree t ON t.id=l.claim_id UNION SELECT m.source_id FROM metrics m JOIN claim_links l ON l.metric_id=m.id JOIN tree t ON t.id=l.claim_id UNION SELECT c.source_id FROM design_claims c JOIN tree t ON t.id=c.id)`).bind(claimId).all<SourceRecord>()).results;
  return {claims,sources};
}
export async function getSourcesForClaims(claimIds:number[]){const sources=new Map<number,SourceRecord>();for(const id of [...new Set(claimIds)].slice(0,100)){for(const source of (await getClaimEvidence(id)).sources)sources.set(source.id,source);}return [...sources.values()];}
export async function getStaleClaims(){return (await db().prepare('SELECT * FROM stale_claims').all<ClaimRecord>()).results;}
export async function getSelection(){const [criteria,weights,assessments]=await Promise.all([db().prepare('SELECT * FROM criteria').all<{code:string;name:string;kind:string;rubric:string}>(),db().prepare('SELECT criterion_code,weight FROM current_weights').all<{criterion_code:string;weight:number}>(),db().prepare('SELECT a.*,s.seed_key AS site_key FROM current_assessments a JOIN sites s ON s.id=a.site_id').all<{site_key:string;criterion_code:string;score:number|null;gate_result:string|null;claim_id:number}>()]);return {criteria:criteria.results,weights:weights.results,assessments:assessments.results};}
