INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S1','Bank of Canada','USD/CAD exchange rate','https://www.bankofcanada.ca/valet/observations/FXUSDCAD/json?recent=3','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S2','Texas Legislature','SB 6 enrolled bill analysis','https://capitol.texas.gov/tlodocs/89R/analysis/html/SB00006F.htm','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S3','Foley & Lardner','PUC proposed large-load interconnection rules (Mar 2026)','https://www.foley.com/insights/publications/2026/03/public-utility-commission-of-texas-issues-proposed-rules-for-large-load-interconn/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S4','POWER Magazine','governor orders audit of the Texas data center queue','https://powermag.com/abbott-orders-full-audit-of-texas-data-center-interconnection-queue-threatens-to-deny-grid-access/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S5','EIA','Electric Power Monthly, Table 5.6.B','https://www.eia.gov/electricity/monthly/epm_table_grapher.php?t=epmt_5_6_b','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S6','ERCOT','commercial markets update (Jan 2025)','https://www.ercot.com/files/docs/2025/01/27/9-3-commercial-markets-update.pdf','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S7','EIA','Texas electricity profile','https://www.eia.gov/electricity/state/texas/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S8','FOX 4','Texas health department Uri death toll','https://www.fox4news.com/news/texas-dshs-reports-higher-death-toll-from-february-winter-storm','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S9','Texas Tribune','Hurricane Beryl outages','https://www.texastribune.org/2024/07/08/hurricane-beryl-texas-damage-updates-rain','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S10','National Weather Service','Austin climate normals','https://www.weather.gov/media/ewx/climate/ATTJuly.pdf','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S11','UTSA','Carnegie classification reaffirmed (2025)','https://utsa.edu/today/2025/02/story/carnegie-classification-reaffirmed.html','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S12','Government of Québec','Bill 2 adopted','https://www.quebec.ca/nouvelles/actualites/details/adoption-du-projet-de-loi-no-2-hausse-des-tarifs-dhydro-quebec-limitee-a-3-pour-les-quebecois-45784','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S13','BLG','data centre regulation in Québec (Jul 2026)','https://www.blg.com/en/insights/2026/07/data-centre-regulation-in-quebec-from-honeyed-promise-to-iron-control','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S14','Radio-Canada','half of electricity requests are data centers','https://ici.radio-canada.ca/nouvelle/2289961/moitie-demandes-electricite-centres-donnees-quebec','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S15','Hydro-Québec','electricity rates (Apr 1, 2026)','https://www.hydroquebec.com/data/documents-donnees/pdf/electricity-rates.pdf','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S16','Hydro-Québec','proposed rate for large data centres','https://news.hydroquebec.com/news/press-releases/all-quebec/hydro-quebec-proposing-regie-energie-new-rate-large-data-centres-adjustment-rate-cryptographic-use-applied-blockchains.html','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S17','CP24','Hydro-Québec data centre rate hearing (Oct 2026)','https://www.cp24.com/news/canada/2026/10/01/hydro-quebec-to-face-off-against-industry-actors-like-google-in-data-centre-hearing/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S18','Hydro-Québec','GHG emission rate 2025','https://www.hydroquebec.com/data/developpement-durable/pdf/2026G195A-4_Emission_GES.pdf','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S19','Hydro-Québec','supply mix 2025','https://www.hydroquebec.com/data/developpement-durable/pdf/2026G195A-1_Quebec.pdf','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S20','Hydro-Québec','1998 ice storm; CBC, April 2023 outages','https://www.hydroquebec.com/ice-storm-1998/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Additional reference: https://www.cbc.ca/1.6802034',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S21','Hydro-Québec','2024 distribution accountability report','https://news.hydroquebec.com/news/press-releases/all-quebec/hydro-quebec-positive-assessment-2024-distribution-activities-published-annual-accountability-report.html','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S22','Environment and Climate Change Canada','Montréal climate normals','https://api.weather.gc.ca/collections/climate-normals/items?CLIMATE_IDENTIFIER=7025250&MONTH=13','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S23','WRI Aqueduct baseline water stress (Resource Watch)','WRI Aqueduct baseline water stress (Resource Watch)','https://resourcewatch.org','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S24','Fingrid','phases of a grid connection agreement','https://www.fingrid.fi/en/grid/grid-connection-agreement-phases/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S25','Fingrid','consumption connections temporarily tight in southern Finland (Jan 2025)','https://www.fingrid.fi/en/news/news/2025/the-connection-of-electricity-consumption-to-the-main-grid-is-temporarily-tight-in-southern-finland','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S26','Fingrid','half-year report 2026','https://www.investegate.co.uk/announcement/gnw/fingrid-oyj--38fe/fingrid-group-s-half-year-report-1-1-30-6-20-/9684352','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S27','Eurostat','non-household electricity prices (nrg_pc_205)','https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/nrg_pc_205?geo=FI&nrg_cons=MWH70000-149999','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S28','Finnish Tax Administration','electricity tax','https://vero.fi/yritykset-ja-yhteisot/verot-ja-maksut/valmisteverotus/sahkovero/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S29','The Star (wire)','Finland drops planned data center support (Sep 2026)','https://www.thestar.com.my/news/world/2026/09/02/finland-drops-planned-financial-support-for-data-centers','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S30','Electricity Maps','Finland grid review 2025','https://www.electricitymaps.com/grid-in-review-2025/finland','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S31','Fingrid','Estlink 2 returns to use (Jun 2025)','https://www.fingrid.fi/en/news/news/2025/estlink-2-electricity-transmission-link-returns-to-commercial-use/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S32','Finnish Meteorological Institute','open data (Kaisaniemi)','https://opendata.fmi.fi/wfs','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S33','WRI','Aqueduct 4.0 country rankings','https://datasets.wri.org/datasets/aqueduct-40-current-and-future-country-rankings','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S34','Mila','about','https://mila.quebec/en/mila/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S35','FCAI','about','https://fcai.fi/about','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S36','TACC','Horizon and Vista announcements','https://tacc.utexas.edu/news/latest-news/2025/11/17/nsf-lccf-horizon-supercomputer-to-power-breakthroughs-for-the-nations-leading-scientists/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S37','CBRE','North American data center trends, first half of 2026','https://www.cbre.com/press-releases/north-american-data-center-demand-continues-to-outpace-supply-despite-record-construction-activity','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S38','Digital Research Alliance of Canada','Rorqual','https://alliancecan.ca/en/services/compute/rorqual','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S39','Government of Canada','Sovereign AI Compute Strategy note','https://search.open.canada.ca/qpnotes/record/ic%2CAIDI-2026-QP-00004','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S40','LUMI documentation and TOP500 entry','LUMI documentation and TOP500 entry','https://docs.lumi-supercomputer.eu/hardware/lumig/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Additional reference: https://www.top500.org/system/180048/',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S41','AMD','LUMI-AI announcement (Aug 2026)','https://newsroom.amd.com/news/amd-instinct-gpus-epyc-cpus-power-lumi-ai-supercomputer/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S42','CSC','Roihu documentation','https://docs.csc.fi/computing/systems-roihu','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S43','UT Arlington','Powering Large Loads: diesel generators','https://uta.pressbooks.pub/poweringlargeloads/chapter/4-diesel-generators/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S44','E&E News','Texas water plan and data centers','https://www.eenews.net/articles/texas-water-plan-ignores-data-center-surge/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S45','Le Nouvelliste','calls for a BAPE review of data centres (Sep 2026)','https://www.lenouvelliste.ca/actualites/environnement/2026/09/17/le-boom-des-centres-de-donnees-ravive-les-appels-a-un-bape-STQ736KECRDFTFHADPME4UZQN4/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S46','Finlex','Environmental Protection Act 527/2014 and decree','https://finlex.fi/api/media/statute/59827/mainPdf/main.pdf','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S47','DLA Piper','EU data centre reporting regulation 2024/1364','https://www.dlapiper.com/en/insights/publications/2024/09/new-data-centre-sustainability-reporting-obligations-introduced-through-eu-20241364-regulation','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S48','Government of Québec','Montréal heat recovery grant; Sustainable Biz, QScale and Énergir','https://sustainablebiz.ca/qscale-partners-with-energir-for-waste-heat-recovery-projects','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S49','Helen','waste heat from new data centre (2026)','https://www.helen.fi/en/news/2026/helen-hyodyntaa-uuden-datakeskuksen-hukkalampoa-helsingin-kaukolammossa','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S50','Microsoft','Finland datacenter region and district heating (2022)','https://news.microsoft.com/europe/2022/03/17/microsoft-announces-intent-to-build-a-new-datacenter-region-in-finland-accelerating-sustainable-digital-transformation-and-enabling-large-scale-carbon-free-district-heating/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S51','IEA','Energy and AI, regional data (Apr 2026), via Our World in Data','https://www.iea.org/data-and-statistics/data-product/energy-and-ai','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Additional reference: https://api.ourworldindata.org/v1/indicators/1295512.metadata.json',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S52','Synergy Research Group','US accounts for 54% of hyperscale capacity (Mar 2025)','https://srgresearch.com/articles/hyperscale-data-center-count-hits-1136-average-size-increases-us-accounts-for-54-of-total-capacity','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S53','AWS','global infrastructure: Regions and Availability Zones','https://aws.amazon.com/about-aws/global-infrastructure/regions_az/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S54','Stanford HAI','AI Index 2026, research and development','https://hai.stanford.edu/ai-index/2026-ai-index-report/research-and-development','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S55','Anthropic','Economic Index: geography (Sep 2025)','https://www.anthropic.com/research/economic-index-geography','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S56','Microsoft','Azure network round-trip latency statistics','https://learn.microsoft.com/en-us/azure/networking/azure-network-latency','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S57','WonderNetwork','global ping statistics (Dallas, Montreal, Helsinki)','https://wondernetwork.com/pings/Dallas','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S58','AWS','data transfer pricing (Price List API, Sep 2026)','https://aws.amazon.com/ec2/pricing/on-demand/','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S59','TeleGeography','IP transit price erosion (2026)','https://resources.telegeography.com/ip-transit-price-erosion-significant-regional-differences-remain','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S60','Internet2 dues and fees; CANARIE connection fees; CSC/Funet','Internet2 dues and fees; CANARIE connection fees; CSC/Funet','https://internet2.edu/community/membership/research-and-education-networks-membership/research-and-education-network-dues-and-fees','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S61','Steptoe','rescission of the AI diffusion rule (2025)','https://www.steptoe.com/en/news-publications/international-compliance-blog/trump-administration-charts-new-path-on-ai-export-controls-with-significant-new-guidance-and-rescission-of-diffusion-rule.html','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S62','Bird & Bird','EU–US Data Privacy Framework upheld (Sep 2025)','https://cm.twobirds.com/en/insights/2025/euus-data-privacy-framework-survives-legal-challenge-what-the-latombe-decision-means-for-internation','research_firm',0,'2026-10-06T00:00:00Z',NULL,'Source catalog imported from phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO sources (seed_key,publisher,title,url,source_type,is_primary,accessed_at,excerpt,notes,verified_by,verified_at) VALUES ('S63','Course instructor','Lesson 06 — Build a DataCenter Challenge','/challenge-brief.pdf','course_material',1,'2026-10-06T00:00:00Z','Proposed facility electrical demand includes computing and cooling. Member commitments and grid energization terms are not yet established.','Assignment supplied with the project.',NULL,NULL) ON CONFLICT DO NOTHING;
