INSERT INTO metrics (seed_key,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('demand-east',(SELECT id FROM demand_regions WHERE seed_key='east'),'demand_share',36.3,'%','2026','estimate',(SELECT id FROM sources WHERE seed_key='S51'),'2026-10-06T00:00:00Z','medium','Rounded allocation from phase-one IEA regional demand and CBRE US-market split; proxy rather than contracted demand.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('demand-central',(SELECT id FROM demand_regions WHERE seed_key='central'),'demand_share',14.4,'%','2026','estimate',(SELECT id FROM sources WHERE seed_key='S51'),'2026-10-06T00:00:00Z','medium','Rounded allocation from phase-one IEA regional demand and CBRE US-market split; proxy rather than contracted demand.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('demand-west',(SELECT id FROM demand_regions WHERE seed_key='west'),'demand_share',11.6,'%','2026','estimate',(SELECT id FROM sources WHERE seed_key='S51'),'2026-10-06T00:00:00Z','medium','Rounded allocation from phase-one IEA regional demand and CBRE US-market split; proxy rather than contracted demand.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('demand-europe',(SELECT id FROM demand_regions WHERE seed_key='europe'),'demand_share',19.5,'%','2026','estimate',(SELECT id FROM sources WHERE seed_key='S51'),'2026-10-06T00:00:00Z','medium','Rounded allocation from phase-one IEA regional demand and CBRE US-market split; proxy rather than contracted demand.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('demand-asia',(SELECT id FROM demand_regions WHERE seed_key='asia'),'demand_share',15.2,'%','2026','estimate',(SELECT id FROM sources WHERE seed_key='S51'),'2026-10-06T00:00:00Z','medium','Rounded allocation from phase-one IEA regional demand and CBRE US-market split; proxy rather than contracted demand.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('demand-rest',(SELECT id FROM demand_regions WHERE seed_key='rest'),'demand_share',3,'%','2026','estimate',(SELECT id FROM sources WHERE seed_key='S51'),'2026-10-06T00:00:00Z','medium','Rounded allocation from phase-one IEA regional demand and CBRE US-market split; proxy rather than contracted demand.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-tx-east',(SELECT id FROM sites WHERE seed_key='tx'),(SELECT id FROM demand_regions WHERE seed_key='east'),'round_trip_latency',39,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','City-to-city ping proxy from phase-one specification, not a campus service-level measurement.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-tx-central',(SELECT id FROM sites WHERE seed_key='tx'),(SELECT id FROM demand_regions WHERE seed_key='central'),'round_trip_latency',23,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','City-to-city ping proxy from phase-one specification, not a campus service-level measurement.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-tx-west',(SELECT id FROM sites WHERE seed_key='tx'),(SELECT id FROM demand_regions WHERE seed_key='west'),'round_trip_latency',45,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','City-to-city ping proxy from phase-one specification, not a campus service-level measurement.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-tx-europe',(SELECT id FROM sites WHERE seed_key='tx'),(SELECT id FROM demand_regions WHERE seed_key='europe'),'round_trip_latency',116,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','City-to-city ping proxy from phase-one specification, not a campus service-level measurement.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-tx-asia',(SELECT id FROM sites WHERE seed_key='tx'),(SELECT id FROM demand_regions WHERE seed_key='asia'),'round_trip_latency',179,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','City-to-city ping proxy from phase-one specification, not a campus service-level measurement.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-tx-rest',(SELECT id FROM sites WHERE seed_key='tx'),(SELECT id FROM demand_regions WHERE seed_key='rest'),'round_trip_latency',147.5,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','Method: mean of Europe and Asia-Pacific city-ping proxies.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-tx-china',(SELECT id FROM sites WHERE seed_key='tx'),(SELECT id FROM demand_regions WHERE seed_key='china'),'round_trip_latency',NULL,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','No service-market latency established for the excluded China region.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-qc-east',(SELECT id FROM sites WHERE seed_key='qc'),(SELECT id FROM demand_regions WHERE seed_key='east'),'round_trip_latency',11,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','City-to-city ping proxy from phase-one specification, not a campus service-level measurement.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-qc-central',(SELECT id FROM sites WHERE seed_key='qc'),(SELECT id FROM demand_regions WHERE seed_key='central'),'round_trip_latency',21,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','City-to-city ping proxy from phase-one specification, not a campus service-level measurement.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-qc-west',(SELECT id FROM sites WHERE seed_key='qc'),(SELECT id FROM demand_regions WHERE seed_key='west'),'round_trip_latency',66,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','City-to-city ping proxy from phase-one specification, not a campus service-level measurement.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-qc-europe',(SELECT id FROM sites WHERE seed_key='qc'),(SELECT id FROM demand_regions WHERE seed_key='europe'),'round_trip_latency',83,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','City-to-city ping proxy from phase-one specification, not a campus service-level measurement.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-qc-asia',(SELECT id FROM sites WHERE seed_key='qc'),(SELECT id FROM demand_regions WHERE seed_key='asia'),'round_trip_latency',208,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','City-to-city ping proxy from phase-one specification, not a campus service-level measurement.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-qc-rest',(SELECT id FROM sites WHERE seed_key='qc'),(SELECT id FROM demand_regions WHERE seed_key='rest'),'round_trip_latency',145.5,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','Method: mean of Europe and Asia-Pacific city-ping proxies.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-qc-china',(SELECT id FROM sites WHERE seed_key='qc'),(SELECT id FROM demand_regions WHERE seed_key='china'),'round_trip_latency',NULL,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','No service-market latency established for the excluded China region.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-hel-east',(SELECT id FROM sites WHERE seed_key='hel'),(SELECT id FROM demand_regions WHERE seed_key='east'),'round_trip_latency',106,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','City-to-city ping proxy from phase-one specification, not a campus service-level measurement.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-hel-central',(SELECT id FROM sites WHERE seed_key='hel'),(SELECT id FROM demand_regions WHERE seed_key='central'),'round_trip_latency',129,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','City-to-city ping proxy from phase-one specification, not a campus service-level measurement.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-hel-west',(SELECT id FROM sites WHERE seed_key='hel'),(SELECT id FROM demand_regions WHERE seed_key='west'),'round_trip_latency',169,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','City-to-city ping proxy from phase-one specification, not a campus service-level measurement.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-hel-europe',(SELECT id FROM sites WHERE seed_key='hel'),(SELECT id FROM demand_regions WHERE seed_key='europe'),'round_trip_latency',30,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','City-to-city ping proxy from phase-one specification, not a campus service-level measurement.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-hel-asia',(SELECT id FROM sites WHERE seed_key='hel'),(SELECT id FROM demand_regions WHERE seed_key='asia'),'round_trip_latency',224,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','City-to-city ping proxy from phase-one specification, not a campus service-level measurement.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-hel-rest',(SELECT id FROM sites WHERE seed_key='hel'),(SELECT id FROM demand_regions WHERE seed_key='rest'),'round_trip_latency',127,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','Method: mean of Europe and Asia-Pacific city-ping proxies.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,demand_region_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('latency-hel-china',(SELECT id FROM sites WHERE seed_key='hel'),(SELECT id FROM demand_regions WHERE seed_key='china'),'round_trip_latency',NULL,'ms','2026','estimate',(SELECT id FROM sources WHERE seed_key='S57'),'2026-10-06T00:00:00Z','medium','No service-market latency established for the excluded China region.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('price-tx',(SELECT id FROM sites WHERE seed_key='tx'),'industrial_electricity_price',67.2,'USD/MWh','2026','estimate',(SELECT id FROM sources WHERE seed_key='S5'),'2026-10-06T00:00:00Z','medium','6.72 cents/kWh × 10; EIA Jan–Jul 2026 industrial average, not a delivered site offer.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('price-qc',(SELECT id FROM sites WHERE seed_key='qc'),'industrial_electricity_price',46.2,'USD/MWh','2026','estimate',(SELECT id FROM sources WHERE seed_key='S15'),'2026-10-06T00:00:00Z','medium','65.9 CAD/MWh divided by 1.4254 CAD/USD (M-FX-CAD-USD, 2026-10-05); excludes proposed tariff.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('price-hel',(SELECT id FROM sites WHERE seed_key='hel'),'industrial_electricity_price',73,'USD/MWh','2026','estimate',(SELECT id FROM sources WHERE seed_key='S27'),'2026-10-06T00:00:00Z','medium','(42.2 + 22.4) EUR/MWh × 1.13 USD/EUR (M-FX-EUR-USD, 2025); combined energy and tax estimate.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,country_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('M-FX-CAD-USD',(SELECT id FROM countries WHERE seed_key='CA'),'fx_rate',0.7015574575557738,'ratio','2026','estimate',(SELECT id FROM sources WHERE seed_key='S1'),'2026-10-06T00:00:00Z','medium','USD per CAD; reciprocal of 1 USD = 1.4254 CAD on 2026-10-05.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,country_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('M-FX-EUR-USD',(SELECT id FROM countries WHERE seed_key='FI'),'fx_rate',1.13,'ratio','2025','estimate',(SELECT id FROM sources WHERE seed_key='S30'),'2026-10-06T00:00:00Z','medium','USD per EUR; 2025 average conversion assumption in phase-one specification.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('carbon-tx',(SELECT id FROM sites WHERE seed_key='tx'),'grid_carbon_intensity',373,'gCO2/kWh','2024','estimate',(SELECT id FROM sources WHERE seed_key='S7'),'2026-10-06T00:00:00Z','medium','Regional electricity carbon estimate in phase-one comparison; not interchangeable with national live lifecycle intensity.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('carbon-qc',(SELECT id FROM sites WHERE seed_key='qc'),'grid_carbon_intensity',7.8,'gCO2/kWh','2025','estimate',(SELECT id FROM sources WHERE seed_key='S18'),'2026-10-06T00:00:00Z','medium','Regional electricity carbon estimate in phase-one comparison; not interchangeable with national live lifecycle intensity.',NULL,NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO metrics (seed_key,site_id,metric_name,value,unit,reporting_period,claim_type,source_id,retrieved_at,confidence,notes,verified_by,verified_at) VALUES ('carbon-hel',(SELECT id FROM sites WHERE seed_key='hel'),'grid_carbon_intensity',66,'gCO2/kWh','2025','estimate',(SELECT id FROM sources WHERE seed_key='S30'),'2026-10-06T00:00:00Z','medium','Regional electricity carbon estimate in phase-one comparison; not interchangeable with national live lifecycle intensity.',NULL,NULL) ON CONFLICT DO NOTHING;
