import { annualEnergyGwh, facilityPowerMw, outageEnergyMwh, proposalData } from '../../lib/db/proposal';
import SystemDiagram from '../../components/SystemDiagram';

export default function Design() {
  const d=proposalData.design;
  return <>
    <section className="page-head"><div className="shell"><span className="eyebrow">Initial design</span><h1>Built for continuity and control.</h1><p>The reference architecture pairs high-density AI compute with redundant power paths, backup generation and closed-loop cooling.</p></div></section>
    <section className="section design-system"><div className="shell"><div className="section-head"><div><span className="eyebrow">System path</span><h2>Power, cooling, network and failure routes.</h2></div></div><SystemDiagram/></div></section>
    <section className="section band"><div className="shell"><div className="section-head"><div><span className="eyebrow">Power envelope</span><h2>A clear operating baseline.</h2></div></div><div className="grid-3"><div className="card"><div className="number">{d.itLoadMw} MW</div><h3>IT demand</h3><p>Assumption for installed compute and supporting IT systems.</p></div><div className="card"><div className="number">{facilityPowerMw()} MW</div><h3>Facility demand</h3><p>Calculation: IT demand multiplied by the {d.pue.toFixed(2)} PUE assumption.</p></div><div className="card"><div className="number">{annualEnergyGwh()} GWh</div><h3>Annual energy</h3><p>Calculation at {d.operatingHours.toLocaleString()} operating hours per year.</p></div></div></div></section>
    <section className="section"><div className="shell"><div className="section-head"><div><span className="eyebrow">Failure walkthroughs</span><h2>How the concept responds.</h2></div></div><div className="grid-2"><div><h3>Largest electrical component fails</h3><div className="step-list"><div className="step">Protection isolates the failed component so the fault does not propagate.</div><div className="step">UPS carries critical load during transfer to the remaining path or backup generation.</div><div className="step">Operators shed noncritical work if available redundancy cannot sustain the full AI load.</div></div></div><div><h3>Grid unavailable for {d.gridOutageHours} hours</h3><div className="step-list"><div className="step">Backup generation starts and the UPS bridges the transition.</div><div className="step">At full facility load, the event requires {outageEnergyMwh().toLocaleString()} MWh of delivered energy · calculation.</div><div className="step">Fuel, emissions permit, refuelling contracts and the exact load-shedding sequence require engineering confirmation.</div></div></div></div></div></section>
    <section className="section band dark"><div className="shell"><span className="eyebrow" style={{color:'#8ce1cd'}}>Grid interface</span><h2>Plan the facility as a grid participant.</h2><p className="lead">The utility sees a peak request of {facilityPowerMw()} MW and modeled annual consumption of {annualEnergyGwh()} GWh. Short-term swings, curtailment terms and impacts on other customers remain part of the interconnection study.</p></div></section>
  </>;
}
