import { annualEnergyGwh, facilityPowerMw, outageEnergyMwh, proposalData } from '../../lib/db/proposal';
import SystemDiagram from '../../components/SystemDiagram';
import { getPublishedDesignInputs } from '../../lib/db/published-design';
import { DesignNarratives } from '../../components/design-narratives';

export const dynamic='force-dynamic';
export default async function Design() {
  const d=await getPublishedDesignInputs();
  const facilityPowerMw=()=>d.itLoadMw*d.pue;
  const annualEnergyGwh=()=>facilityPowerMw()*d.operatingHours/1000;
  const outageEnergyMwh=()=>facilityPowerMw()*d.gridOutageHours;
  return <>
    <section className="page-head"><div className="shell"><span className="eyebrow">Initial design</span><h1>Built for continuity and control.</h1><p>The reference architecture pairs high-density AI compute with redundant power paths, backup generation and closed-loop cooling.</p></div></section>
    <section className="section design-system"><div className="shell"><div className="section-head"><div><span className="eyebrow">System path</span><h2>Power, cooling, network and failure routes.</h2></div><a className="text-link" href="/workspace?role=admin#design-settings">Manage design assumptions ↗</a></div><SystemDiagram itLoadMw={d.itLoadMw} pue={d.pue}/></div></section>
    <section className="section band"><div className="shell"><div className="section-head"><div><span className="eyebrow">Power envelope</span><h2>A clear operating baseline.</h2></div></div><div className="grid-3"><div className="card"><div className="number"><a href="/evidence#design-inputs">{d.itLoadMw} MW</a></div><h3>IT demand</h3><p>Assumption for installed compute and supporting IT systems.</p></div><div className="card"><div className="number"><a href="/evidence#facility-load">{facilityPowerMw()} MW</a></div><h3>Facility demand</h3><p>Calculation: IT demand multiplied by the {d.pue.toFixed(2)} PUE assumption.</p></div><div className="card"><div className="number"><a href="/evidence#annual-energy">{annualEnergyGwh()} GWh</a></div><h3>Annual energy</h3><p>Calculation at {d.operatingHours.toLocaleString()} operating hours per year.</p></div></div></div></section>
    <section className="section"><div className="shell"><div className="section-head"><div><span className="eyebrow">Failure walkthroughs</span><h2>How the concept responds.</h2></div></div><div className="grid-2"><div><h3>Largest electrical component fails</h3><div className="step-list"><div className="step">Protection isolates the failed component so the fault does not propagate.</div><div className="step">UPS carries critical load during transfer to the remaining path or backup generation.</div><div className="step">Operators shed noncritical work if available redundancy cannot sustain the full AI load.</div></div></div><div><h3>Grid unavailable for {d.gridOutageHours} hours</h3><div className="step-list"><div className="step">Backup generation starts and the UPS bridges the transition.</div><div className="step">At full facility load, the event requires {outageEnergyMwh().toLocaleString()} MWh of delivered energy · calculation.</div><div className="step">Fuel, emissions permit, refuelling contracts and the exact load-shedding sequence require engineering confirmation.</div></div></div></div></div></section>
    <section className="section band dark"><div className="shell"><span className="eyebrow" style={{color:'#8ce1cd'}}>Grid interface</span><h2>Plan the facility as a grid participant.</h2><p className="lead">The utility sees a peak request of {facilityPowerMw()} MW and modeled annual consumption of {annualEnergyGwh()} GWh. Short-term swings, curtailment terms and impacts on other customers remain part of the interconnection study.</p></div></section>
    <section className="section band" id="design-record"><div className="shell"><div className="section-head"><div><span className="eyebrow">Design record</span><h2>The initial design, field by field.</h2></div><a className="text-link" href="/evidence#claim-ledger">Claims and sources ↗</a></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Field</th><th>Initial design</th><th>Type</th></tr></thead><tbody>{[
      ['Country and region',`${d.location}; ${d.referenceCity} is the reference geography. The precise site depends on a utility and property study.`,'design decision'],
      ['Grid connection','Utility supply through two transformers, a primary and an alternate path, into common switchgear. Energization date and upgrade cost are not established.','design decision · unknown'],
      ['Backup power',`UPS bridges every transfer; fuel-backed generators carry a ${d.gridOutageHours}-hour grid outage. Fuel quantity and refuelling contracts are not established.`,'design decision · unknown'],
      ['Cooling',`${d.cooling}, carrying heat from the compute halls to non-evaporative heat rejection.`,'design decision'],
      ['Water','No routine evaporative water demand. Initial fill and make-up volumes are not established.','design decision · unknown'],
      ['Network',`A research network connects the compute halls and shared storage to member institutions. Site scoring uses a ${d.latencyThresholdMs} ms round-trip threshold to demand.`,'assumption'],
      ['Storage','Shared storage for datasets and training checkpoints stays on the critical-power path. Capacity and backup copies are not established.','design decision · unknown'],
      ['Electricity sources','The Texas grid mix shown on the country comparison. No on-site solar, wind, gas or storage is counted towards supply, and annual renewable certificates are not counted as firm hourly power.','design decision'],
      ['Uptime target','Not established. Members must first set availability and recovery objectives for each workload.','unknown'],
    ].map(([field,text,type])=><tr key={field}><th scope="row">{field}</th><td>{text}</td><td><span className="tag gray">{type}</span></td></tr>)}</tbody></table></div>
    <div className="card" style={{marginTop:24}} id="uptime-data"><h3>Data needed to show the design meets an uptime target</h3><ul className="list"><li>Utility outage history and the written connection offer for the chosen site.</li><li>Transformer ratings and a selective-coordination study for the remaining path after a fault.</li><li>Tested UPS autonomy and witnessed transfer tests at full load.</li><li>Generator electrical yield per unit of fuel, usable tank capacity and a refuelling contract.</li><li>Cooling pump and heat-rejection redundancy at peak summer temperature.</li><li>Workload-specific availability and recovery objectives agreed by members.</li></ul></div></div></section>
    <section className="section"><div className="shell"><h2>Requirements, resilience and grid obligations.</h2><DesignNarratives keys={['workload_requirements','failure_largest_component','failure_grid_48h','grid_impact']}/></div></section>
  </>;
}
