import { applyScenario,investmentModel,modelDefinitions,numericInput,sensitivity } from '../../lib/db/proposal';
import { getModelInputs } from '../../lib/db/model-inputs';
import { DesignNarratives } from '../../components/design-narratives';
import { getFundingRequirements } from '../../lib/db/content';
import { getPublicDesign } from '../../lib/db/evidence';
import { getDecisions } from '../../lib/db/decisions';
import { CommitteeDecisionForm } from '../../components/committee-decision';
import { authEnabled } from '../../lib/access';
import { getMember } from '../../lib/db/membership';
import { getChatGPTUser } from '../chatgpt-auth';
export const dynamic='force-dynamic';
type Params=Record<string,string|string[]|undefined>;
const scenarios=[['base','Base case'],['grid-delay','Additional three-month delay'],['grid-year-delay','Required stress: one-year grid delay'],['half-utilization','Required stress: half forecast GPU use']];
const money=(n:number)=>`${n<0?'−':''}$${Math.abs(n).toFixed(1)}m`;
export default async function Investment({searchParams}:{searchParams:Promise<Params>}){
 const params=await searchParams,defaults=await getModelInputs();
 const funding=await getFundingRequirements();
 const publicDesign=await getPublicDesign();
 const decisions=publicDesign?await getDecisions(publicDesign.id):[];
 // Recorder identity is shown only to signed-in members of the same team.
 const identity=authEnabled()?await getChatGPTUser():null;
 const viewer=identity?await getMember(identity.userId):null;
 const outcomeLabel={approve:'Approved',reject:'Rejected',send_back:'Sent back for more evidence'} as const;
 const scenario=typeof params.scenario==='string'&&scenarios.some(([k])=>k===params.scenario)?params.scenario:'base';
 const option=typeof params.option==='string'&&['build','lease','hybrid'].includes(params.option)?params.option:'build';
 const values={...defaults,...Object.fromEntries(modelDefinitions.map(([key,,,min,max])=>[key,numericInput(params[key],min,max)??defaults[key]]))};
 const input=applyScenario(values,scenario);let error='';let options:ReturnType<typeof investmentModel>=[];
 try{options=investmentModel(input);}catch(e){error=e instanceof Error?e.message:'Please check model assumptions.';}
 const selected=options.find(o=>o.id===option);
 const field=([key,label,unit,min,max]:typeof modelDefinitions[number])=><div className="field" key={key}><label htmlFor={key}>{label} <span className="subtle">({unit})</span></label><input id={key} name={key} type="number" min={min} max={max} step="any" defaultValue={values[key]}/></div>;
 return <>
 <section className="page-head"><div className="shell"><span className="eyebrow">Investment case</span><h1>Make the economics visible.</h1><p>Build, lease and staged hybrid under the same demand assumptions. Separate facility and GPU cash flows expose delay, replacement and unused-capacity costs.</p></div></section>
 <section className="section"><div className="shell"><div className="section-head"><h2>Change one input. See the effect.</h2><a className="text-link" href="/investment?example=1">Reset to stored example ↗</a></div><form method="get" action="/investment" className="card"><div className="field-grid"><div className="field"><label htmlFor="scenario">Scenario</label><select id="scenario" name="scenario" defaultValue={scenario}>{scenarios.map(([k,label])=><option key={k} value={k}>{label}</option>)}</select></div><div className="field"><label htmlFor="option">Cost path</label><select id="option" name="option" defaultValue={option}><option value="build">Build and own</option><option value="lease">Lease capacity</option><option value="hybrid">Phased hybrid</option></select></div>{modelDefinitions.slice(0,11).map(field)}</div><details style={{marginTop:24}}><summary>Facility, GPU fleet, financing and operating assumptions</summary><div className="field-grid" style={{marginTop:20}}>{modelDefinitions.slice(11).map(field)}</div></details><button className="button" style={{marginTop:24}} type="submit">Recalculate scenario ↗</button></form><p className="subtle">Base grid delay: {defaults.gridDelayMonths} months (about two weeks) after planned construction. The other cases add three or twelve months. All inputs are planning assumptions, not quotes or commitments. Visitor changes are not saved.</p>{error&&<p role="alert" className="card">{error}</p>}</div></section>
 <section className="section band"><div className="shell"><div className="section-head"><div><span className="eyebrow">{scenarios.find(([k])=>k===scenario)?.[1]}</span><h2>Three delivery paths.</h2></div><a className="text-link" href="/evidence#investment-model">Inputs and formulas ↗</a></div><div className="grid-3">{options.map(o=><article key={o.id} className={o.id==='hybrid'?'card accent':'card'}><h3>{o.name}</h3><ul className="list"><li>Funding before owned-site opening<br/><strong>{money(o.beforeOpeningWithDelay)}</strong></li><li>Annual operating run rate<br/><strong>{money(o.annual)}</strong></li><li>Ten-year cost / productive GPU-hour<br/><strong>{o.costPerProductiveHour===null?'Not defined':`$${o.costPerProductiveHour.toFixed(2)}`}</strong></li><li>Capital at risk if stopped after year three<br/><strong>{money(o.capitalAtRiskWithDelay)}</strong></li><li>Net present cash flow<br/><strong>{money(o.npv)}</strong></li><li>Annual cost allocated to unused capacity<br/><strong>{money(o.annualUnusedCapacityCost)}</strong></li></ul><p className="subtle">Calculation · {scenario} · {o.id==='lease'?'Lease begins immediately':`Owned service begins in month ${o.openingMonth.toFixed(1)}`}</p></article>)}</div></div></section>
 <section className="section"><div className="shell"><span className="eyebrow">Ten-year cash flow · calculation · {scenario}</span><h2>{selected?.name??'Check model inputs'}</h2>{selected&&<><div className="grid-3"><div className="card"><h3>Facility construction</h3><p className="number">{money(selected.facilityCapital)}</p><p>Separate from land, grid and GPU fleet.</p></div><div className="card"><h3>Grid + land</h3><p className="number">{money(selected.gridCapital+selected.landCapital)}</p><p>Grid {money(selected.gridCapital)} · land {money(selected.landCapital)}.</p></div><div className="card"><h3>Initial GPU fleet</h3><p className="number">{money(selected.gpuCapital)}</p><p>Replaced every {values.replacementYears} operating years.</p></div></div><div className="table-scroll" style={{marginTop:24}}><table className="data-table"><thead><tr>{['Year','Facility + land + grid','GPU fleet','Operations','Delay','Interest','GPU replacement','Member recovery','Net cash','Cumulative'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{selected.rows.map(r=><tr key={r.year}><td>{r.year}</td>{[r.facility+r.land+r.grid,r.gpu,r.operating,r.delay,r.financing,r.replacement,r.recovery,r.net,r.cumulative].map((v,j)=><td key={j}>{money(v)}</td>)}</tr>)}</tbody></table></div><details style={{marginTop:24}}><summary>Operating and funding detail</summary><div className="table-scroll"><table className="data-table"><thead><tr>{['Year','Electricity','Staff','Maintenance','Other operations','Lease','Idle cost allocation','Debt drawn','Principal repaid','Equity cash flow','Productive GPU-hours'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{selected.rows.map(r=><tr key={r.year}><td>{r.year}</td>{[r.electricity,r.staffing,r.maintenance,r.otherOperations,r.lease,r.unusedCapacityCost,r.debtDraw,r.debtPrincipal,r.equityNet].map((v,j)=><td key={j}>{money(v)}</td>)}<td>{Math.round(r.productiveHours).toLocaleString()}</td></tr>)}</tbody></table></div></details><p className="subtle">Nominal USD. Project cash includes all capital and interest; equity cash adds loan draws and deducts principal repayment. Other operations includes insurance, water, network and property costs within the entered total. Lease prices include power and equipment refresh. Idle cost allocates costs already included. No terminal asset sale is assumed; year-ten debt remaining: {money(selected.outstandingDebt)}.</p></>}</div></section>
 <section className="section band"><div className="shell"><span className="eyebrow">Required comparison · calculations</span><h2>Base case and both challenge stresses.</h2><div className="table-scroll"><table className="data-table"><thead><tr><th>Scenario / option</th><th>Before opening</th><th>Annual operations</th><th>Cost / GPU-hour</th><th>Capital at risk</th></tr></thead><tbody>{!error&&['base','grid-year-delay','half-utilization'].flatMap(s=>investmentModel(applyScenario(values,s)).map(o=><tr key={`${s}-${o.id}`}><td>{scenarios.find(([k])=>k===s)?.[1]}<br/>{o.name}</td><td>{money(o.beforeOpeningWithDelay)}</td><td>{money(o.annual)}</td><td>{o.costPerProductiveHour===null?'Not defined':`$${o.costPerProductiveHour.toFixed(2)}`}</td><td>{money(o.capitalAtRiskWithDelay)}</td></tr>))}</tbody></table></div></div></section>
 <section className="section" id="sensitivity"><div className="shell"><span className="eyebrow">Sensitivity analysis · calculations · current inputs</span><h2>Which assumption moves the answer most.</h2><p className="lead">Each input moves 25% down and up from the values above while everything else stays fixed. Rows are ordered by the largest change in ten-year cost per productive GPU-hour.</p><div className="table-scroll"><table className="data-table"><thead><tr><th>Input</th><th>Low / high value</th><th>Build and own</th><th>Lease capacity</th><th>Phased hybrid</th></tr></thead><tbody>{!error&&sensitivity(values).map(r=><tr key={r.key}><th scope="row">{r.label}</th><td>{+r.low.toFixed(2)} / {+r.high.toFixed(2)} {r.unit}</td>{[0,1,2].map(i=><td key={i}>{[r.lowCost,r.highCost].map(c=>c?.[i]==null?'Outside model range':`$${c[i]!.toFixed(2)}`).join(' → ')}</td>)}</tr>)}</tbody></table></div><p className="subtle">Values are cost per productive GPU-hour at the low and high input. Moved values stay within each input’s allowed range. "Outside model range" means the moved value breaks a model rule, for example build capital no longer covering the GPU fleet.</p></div></section>
 <section className="section" id="governance"><div className="shell"><span className="eyebrow">Governance · proposed design decisions</span><h2>Shared access needs enforceable rules.</h2><div className="grid-3"><article className="card"><h3>Ownership and control</h3><p>A university-owned consortium owns the facility and research-data policies. Contract construction, utility supply, specialist maintenance and overflow cloud capacity. A representative board admits members and approves pricing; an independent scientific panel resolves research/teaching conflicts.</p></article><article className="card"><h3>Capacity and fairness</h3><p>Allocate reservations against take-or-pay commitments, protect a teaching and small-institution pool, and release unused reservations explicitly. Publish allocations and actual usage with an appeal process. Set a single-member discretionary-use cap before expansion.</p></article><article className="card"><h3>Costs and risk</h3><p>Allocate fixed costs by reservation and variable costs by metered productive use. Sponsors bear grid-delay risk until contractual transfer; members bear committed-demand risk. Withdrawal requires notice, a replacement member or payment of unrecovered commitments.</p></article></div></div></section>
 <section className="section band" id="funding-gates"><div className="shell"><h2>Evidence before capital.</h2><div className="grid-3">{[['Development equity','Site control, member demand survey, allocation rules, preliminary utility response and capped diligence budget.'],['Construction debt','Written grid schedule and upgrade price, permits, construction contract, resilience study and take-or-pay commitments.'],['Equipment finance','GPU quotations, acceptance criteria, replacement plan, utilization commitments and member credit support.']].map(([title,text])=><article className="card" key={title}><span className="tag gray">Required evidence</span><h3>{title}</h3><p>{text}</p><a className="text-link" href="/evidence?type=unknown#claim-ledger">Inspect open conditions ↗</a></article>)}</div></div></section>
 <section className="section dark"><div className="shell"><span className="eyebrow">Recommendation</span><h2>Approve diligence. Do not approve the full build.</h2><p className="lead">Start with leased access and a staged hybrid option. Release owned capacity only against a priced utility agreement, signed productive demand and a validated resilience design. Reconsider if Québec offers better grid terms, workloads shift away from latency-sensitive use, or Texas interconnection constraints change.</p></div></section>
 <section className="section band" id="committee-decision"><div className="shell"><span className="eyebrow">Investment committee</span><h2>Approve, reject or send back.</h2><div className="grid-2"><div className="card"><h3>Decision record</h3>{decisions.length?<ul className="list">{decisions.map(d=><li key={d.id}><span className={`tag ${d.outcome==='approve'?'':'amber'}`}>Round {d.round} · {outcomeLabel[d.outcome]}</span><p style={{marginTop:10}}>{d.reason}</p><p className="subtle">Recorded {d.recordedAt.slice(0,16).replace('T',' ')} UTC by {viewer&&publicDesign&&viewer.teamId===publicDesign.team_id?d.recorderEmail??`member ${d.recordedBy}`:'a committee member'}</p></li>)}</ul>:<p>No committee decision has been recorded yet.</p>}</div><CommitteeDecisionForm/></div></div></section>
 <section className="section"><div className="shell"><h2>Allocation policy and funding evidence.</h2><DesignNarratives keys={['capacity_sharing']}/><div className="grid-3" style={{marginTop:24}}>{funding.map(f=><article className="card" key={f.requirement_id}><span className="tag gray">{f.status}</span><h3>{f.stage.replaceAll('_',' ')}</h3><p>{f.requirement_text}</p><a className="text-link" href="/evidence#claim-ledger">Evidence trail ↗</a></article>)}</div></div></section>
 </>;
}
