// Materialize the existing phase-one specification; this does not fetch or invent evidence.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const doc = readFileSync(new URL('../docs/phase-01-define-website.md', import.meta.url), 'utf8');
const proposal = JSON.parse(readFileSync(new URL('./data/proposal.json', import.meta.url), 'utf8'));
const date = '2026-10-06T00:00:00Z';
const files = Object.fromEntries(['vocabulary','places','sources','metrics','design','criteria','assessments','claims'].map(k=>[k,{}]));
const ref=(table,key)=>({ref:table,key});
const put=(file,table,row)=>(files[file][table]??=[]).push(row);
const stamp=(key,fields)=>({seed_key:key,...fields});
const units=['MW','GW','GWh','TWh','%','gCO2/kWh','count','USD/MWh','USD/TB','ms','score','months','hours','ratio','CDD','minutes','USD/CAD','EUR/USD'];
units.forEach(code=>put('vocabulary','units',{code,description:code}));
const definitions=[['dc_electricity_use','TWh','demand_region'],['dc_capacity_in_service','MW','country'],['datacenter_count','count','country'],['industrial_electricity_price','USD/MWh','site'],['wholesale_electricity_price','USD/MWh','site'],['electricity_tax','USD/MWh','site'],['grid_carbon_intensity','gCO2/kWh','site'],['cooling_degree_days','CDD','site'],['share_hours_below_18c','%','site'],['water_stress_score','score','site'],['avg_outage_minutes_per_customer','minutes','site'],['r1_university_count','count','site'],['ai_research_faculty','count','site'],['leasable_gpu_count','count','site'],['large_load_threshold_mw','MW','site'],['grid_connection_months','months','site'],['round_trip_latency','ms','site_to_region'],['data_transfer_price','USD/TB','site'],['fx_rate','ratio','country'],['demand_share','%','demand_region']];
definitions.forEach(([name,unit,subject])=>put('vocabulary','metric_definitions',{name,description:name.replaceAll('_',' '),unit,subject,min_value:0,max_value:null}));
const params=[['it_load_mw',20,'MW',0.1,2000],['pue',1.25,'ratio',1,3],['operating_hours',8760,'hours',1,8760],['latency_threshold_ms',50,'ms',0,1000]];
params.forEach(([name,value,unit,min_value,max_value])=>{put('vocabulary','parameter_definitions',{name,description:name.replaceAll('_',' '),unit,min_value,max_value,user_adjustable:1});put('design','design_parameters',stamp(`P-${name}`,{design_id:ref('designs','university-design'),name,value,claim_type:'assumption',rationale:'Baseline defined in the challenge brief and phase-one design specification.',created_at:date}));});
const countries=[['US','United States','North America'],['CA','Canada','North America'],['FI','Finland','Europe']];
countries.forEach(([key,name,region])=>put('places','countries',stamp(key,{name,region})));
const sites=[['tx','US','Texas','Dallas'],['qc','CA','Québec','Montréal'],['hel','FI','Helsinki','Helsinki']];
sites.forEach(([key,country,name,city])=>put('places','sites',stamp(key,{country_id:ref('countries',country),name,proxy_city:city,notes:'Candidate metro; final parcel and utility connection require a site-specific offer.'})));
const regions=[['east','US East','New York / Washington / Boston',36.3],['central','US Central + Canada/Mexico','Chicago',14.4],['west','US West','San Francisco',11.6],['europe','Europe','Frankfurt / London',19.5],['asia','Asia-Pacific excluding China','Tokyo / Singapore',15.2],['rest','Rest of world','Europe / Asia proxy',3],['china','China','Not addressable',null]];
regions.forEach(([key,name,proxy,share])=>put('places','demand_regions',stamp(key,{name,proxy_cities:proxy,addressable:key==='china'?0:1,notes:key==='china'?'Excluded by consortium service-market design decision.':'Demand proxy, not signed member demand.'})));
const sourceLines=doc.split('\n').filter(l=>/^\| S\d+ \|/.test(l));
sourceLines.forEach(line=>{const [key,label,urls]=line.split('|').slice(1,4).map(s=>s.trim());const split=label.indexOf(',');put('sources','sources',stamp(key,{publisher:split<0?label:label.slice(0,split),title:split<0?label:label.slice(split+1).trim(),url:urls.split(' ; ')[0],source_type:'research_firm',is_primary:0,accessed_at:date,excerpt:null,notes:urls.includes(' ; ')?`Additional reference: ${urls.split(' ; ').slice(1).join('; ')}`:'Source catalog imported from phase-one specification.',verified_by:null,verified_at:null}));});
put('sources','sources',stamp('S63',{publisher:'Course instructor',title:'Lesson 06 — Build a DataCenter Challenge',url:'/challenge-brief.pdf',source_type:'course_material',is_primary:1,accessed_at:date,excerpt:'Proposed facility electrical demand includes computing and cooling. Member commitments and grid energization terms are not yet established.',notes:'Assignment supplied with the project.',verified_by:null,verified_at:null}));
put('design','teams',stamp('university-demo-team',{name:'University AI infrastructure team',course_section:null}));
put('design','designs',stamp('university-design',{team_id:ref('teams','university-demo-team'),name:proposal.design.name,selected_country_id:ref('countries','US'),selected_site_id:ref('sites','tx'),design_summary:'Stage-gated hybrid; Texas reference location, conditional on utility and member commitments.',created_at:date,updated_at:date}));
[['base','Base case','base','Small delay assumption: 0.5 months.'],['grid-delay','Three-month additional delay','variant','Sensitivity requested by the team.'],['grid-year-delay','One-year grid delay','stress','Required challenge stress: full grid power delayed one year.'],['half-utilization','Half forecast utilization','stress','Required challenge stress: utilization is half the base forecast.']].forEach(([key,name,kind,description])=>put('design','scenarios',stamp(key,{design_id:ref('designs','university-design'),name,kind,description,created_at:date})));
function claim(key,text,type='assumption',extra={}) {put('claims','design_claims',stamp(key,{design_id:ref('designs','university-design'),claim_text:text,claim_type:type,value:null,unit:null,calc_key:null,source_id:null,status:'draft',confidence:'medium',topic:'site_selection',created_at:date,...extra}));}
function link(claimKey,table,key,role='evidence'){const column={sources:'source_id',metrics:'metric_id',design_claims:'input_claim_id',parameter_definitions:'parameter_name'}[table];put('claims','claim_links',stamp(`L-${claimKey}-${table}-${key}`,{claim_id:ref('design_claims',claimKey),link_role:role,[column]:table==='parameter_definitions'?key:ref(table,key)}));}
claim('selection','Selected site: Texas, conditional on utility offers and signed member demand.','design_decision');
claim('china-excluded','China is excluded from the addressable service market for the consortium.','design_decision');link('china-excluded','sources','S61');
params.forEach(([name,value,unit])=>{claim(`assumption-${name}`,`${name.replaceAll('_',' ')} is a chosen baseline, not a facility measurement.`,'assumption',{value,unit,topic:'design'});link(`assumption-${name}`,'parameter_definitions',name,'input');});
[['facility_power_mw','Facility electrical power','MW',['it_load_mw','pue']],['annual_energy_gwh','Annual facility electricity','GWh',['it_load_mw','pue','operating_hours']]].forEach(([key,text,unit,inputs])=>{claim(key,text,'calculation',{unit,calc_key:key,topic:'power'});inputs.forEach(p=>link(key,'parameter_definitions',p,'input'));});
const criterionRows=doc.split('\n').filter(l=>/^\| K\d+ \|/.test(l)&&l.split('|').length===9);
criterionRows.forEach(line=>{const [code,name,w,rationale,five,three,one]=line.split('|').slice(1,-1).map(s=>s.trim().replaceAll('**',''));put('criteria','criteria',{code,kind:'score',name,measure:name,rubric:JSON.stringify({'5':five,'3':three,'1':one})});put('criteria','criterion_weights',stamp(`W-${code}`,{criterion_code:code,weight:Number(w),rationale,created_at:date}));});
for(const [code,test] of [['G1','Grid connection legally and practically obtainable'],['G2','No law prohibits the proposed facility'],['G3','No unmitigable single hazard']]) put('criteria','criteria',{code,kind:'gate',name:test,measure:test,rubric:'Conditional until site-specific due diligence closes.'});
const citations={K10:[['S51','S57'],['S51','S57'],['S51','S57']],K1:[['S2','S4'],['S12','S14'],['S24','S25']],K2:[['S5','S6'],['S15','S16'],['S27','S28']],K4:[['S8','S9'],['S20','S21'],['S26','S31']],K6:[['S11'],['S34'],['S35']],K3:[['S7'],['S18'],['S30']],K5:[['S10','S44'],['S22','S23'],['S32','S33']],K7:[['S36'],['S38','S39'],['S40','S41']],K8:[['S43','S44'],['S45'],['S46','S47']],K9:[['S49'],['S48'],['S49','S50']],K11:[['S58','S60'],['S58','S60'],['S58','S60']]};
sites.forEach(([site,,name],index)=>{proposal.criteria.forEach((c,j)=>{const key=`A-${site}-${c.id}`;const score=c.id==='K11'?null:proposal.candidates[index].scores[j];claim(key,`${name}: ${files.criteria.criteria.find(x=>x.code===c.id)?.name}. ${score===null?'No differentiating score; weight is zero.':`Judgment score ${score} on the phase-one rubric; subject to the cited conditions.`}`,'estimate');put('assessments','site_assessments',stamp(key,{criterion_code:c.id,site_id:ref('sites',site),score,gate_result:null,claim_id:ref('design_claims',key),created_at:date}));(citations[c.id][index]).forEach(s=>link(key,'sources',s));link('selection','design_claims',key,'input');});['G1','G2','G3'].forEach(code=>{const key=`A-${site}-${code}`;claim(key,`${name}: ${code} is conditional on site-specific legal, utility and resilience diligence.`,'estimate');link(key,'sources',citations.K1[index][0]);put('assessments','site_assessments',stamp(key,{criterion_code:code,site_id:ref('sites',site),score:null,gate_result:'conditional',claim_id:ref('design_claims',key),created_at:date}));link('selection','design_claims',key,'input');});claim(`grid-${site}`,`${name}: utility connection cost and energization date are not established; obtain a written offer.`,'unknown',{topic:'power'});});
function metric(key,name,value,unit,subject,source,notes,period='2026',type='estimate'){put('metrics','metrics',stamp(key,{...subject,metric_name:name,value,unit,reporting_period:period,claim_type:type,source_id:ref('sources',source),retrieved_at:date,confidence:'medium',notes,verified_by:null,verified_at:null}));}
// Demand shares are the rounded, published phase-one allocation; preserve their precision.
files.metrics.metrics=[];
regions.forEach(([region,,,share])=>{if(share!==null)metric(`demand-${region}`,'demand_share',share,'%',{demand_region_id:ref('demand_regions',region)},'S51','Rounded allocation from phase-one IEA regional demand and CBRE US-market split; proxy rather than contracted demand.');});
const latency=[[39,23,45,116,179,147.5,null],[11,21,66,83,208,145.5,null],[106,129,169,30,224,127,null]];
sites.forEach(([site],i)=>regions.forEach(([region],j)=>metric(`latency-${site}-${region}`,'round_trip_latency',latency[i][j],'ms',{site_id:ref('sites',site),demand_region_id:ref('demand_regions',region)},'S57',j===6?'No service-market latency established for the excluded China region.':j===5?'Method: mean of Europe and Asia-Pacific city-ping proxies.':'City-to-city ping proxy from phase-one specification, not a campus service-level measurement.')));
[['tx',67.2,'S5','6.72 cents/kWh × 10; EIA Jan–Jul 2026 industrial average, not a delivered site offer.'],['qc',46.2,'S15','65.9 CAD/MWh divided by 1.4254 CAD/USD (M-FX-CAD-USD, 2026-10-05); excludes proposed tariff.'],['hel',73,'S27','(42.2 + 22.4) EUR/MWh × 1.13 USD/EUR (M-FX-EUR-USD, 2025); combined energy and tax estimate.']].forEach(([site,value,source,notes])=>metric(`price-${site}`,'industrial_electricity_price',value,'USD/MWh',{site_id:ref('sites',site)},source,notes));
metric('M-FX-CAD-USD','fx_rate',1/1.4254,'ratio',{country_id:ref('countries','CA')},'S1','USD per CAD; reciprocal of 1 USD = 1.4254 CAD on 2026-10-05.');
metric('M-FX-EUR-USD','fx_rate',1.13,'ratio',{country_id:ref('countries','FI')},'S30','USD per EUR; 2025 average conversion assumption in phase-one specification.','2025');
claim('currency-conversion','Converted site prices use the recorded period-specific currency assumptions.','assumption',{topic:'economics'});['M-FX-CAD-USD','M-FX-EUR-USD'].forEach(k=>link('currency-conversion','metrics',k,'input'));
[['tx',373,'S7','2024'],['qc',7.8,'S18','2025'],['hel',66,'S30','2025']].forEach(([site,value,source,period])=>metric(`carbon-${site}`,'grid_carbon_intensity',value,'gCO2/kWh',{site_id:ref('sites',site)},source,'Regional electricity carbon estimate in phase-one comparison; not interchangeable with national live lifecycle intensity.',period));
proposal.conditions.forEach((text,i)=>claim(`condition-${i+1}`,text,'unknown',{topic:'approval'}));
proposal.reversalTriggers.forEach((text,i)=>claim(`reversal-${i+1}`,text,'unknown',{topic:'reversal_trigger'}));
claim('member-demand','No institution has signed a long-term computing commitment; productive demand remains to be contracted.','fact',{source_id:ref('sources','S63'),topic:'governance'});link('member-demand','sources','S63');
for(const [name,tables] of Object.entries(files)){mkdirSync(new URL('./data/',import.meta.url),{recursive:true});writeFileSync(new URL(`./data/${name}.json`,import.meta.url),JSON.stringify({seed_version:'seed-2026-10-06-v1',...tables},null,2)+'\n');}
console.log('Materialized existing specification into eight reviewable seed data files.');
