import { index, integer, real, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

// The immutable migration is the full database contract. These Drizzle
// definitions give server code typed access to the Phase 2 records.
export const units = sqliteTable('units', { code: text().primaryKey(), description: text().notNull() });
export const metricDefinitions = sqliteTable('metric_definitions', { name: text().primaryKey(), description: text().notNull(), unit: text().notNull().references(() => units.code), subject: text().notNull(), minValue: real('min_value'), maxValue: real('max_value') });
export const parameterDefinitions = sqliteTable('parameter_definitions', { name: text().primaryKey(), description: text().notNull(), unit: text().notNull().references(() => units.code), minValue: real('min_value'), maxValue: real('max_value'), userAdjustable: integer('user_adjustable').notNull().default(0) });
export const teams = sqliteTable('teams', { id: integer().primaryKey({ autoIncrement: true }), name: text().notNull().unique(), courseSection: text('course_section') });
export const users = sqliteTable('users', { id: integer().primaryKey({ autoIncrement: true }), authenticatedUserId: text('authenticated_user_id').notNull().unique(), email: text(), teamId: integer('team_id').references(() => teams.id), role: text().notNull().default('viewer'), courseSection: text('course_section'), rulesAcceptedAt: text('rules_accepted_at'), registeredAt: text('registered_at').notNull() });
export const countries = sqliteTable('countries', { id: integer().primaryKey({ autoIncrement: true }), name: text().notNull().unique(), region: text() });
export const sites = sqliteTable('sites', { id: integer().primaryKey({ autoIncrement: true }), countryId: integer('country_id').notNull().references(() => countries.id), name: text().notNull().unique(), proxyCity: text('proxy_city').notNull(), notes: text() });
export const demandRegions = sqliteTable('demand_regions', { id: integer().primaryKey({ autoIncrement: true }), name: text().notNull().unique(), proxyCities: text('proxy_cities').notNull(), addressable: integer().notNull().default(1), notes: text() });
export const sources = sqliteTable('sources', { id: integer().primaryKey({ autoIncrement: true }), publisher: text().notNull(), title: text().notNull(), url: text().notNull(), sourceType: text('source_type').notNull(), isPrimary: integer('is_primary').notNull(), publicationDate: text('publication_date'), accessedAt: text('accessed_at').notNull(), excerpt: text(), notes: text(), supersedesSourceId: integer('supersedes_source_id').references(() => sources.id) });
export const refreshRuns = sqliteTable('refresh_runs', { id: integer().primaryKey({ autoIncrement: true }), sourceKey: text('source_key').notNull(), startedAt: text('started_at').notNull(), finishedAt: text('finished_at').notNull(), status: text().notNull(), rowsAdded: integer('rows_added').notNull().default(0), error: text(), triggeredBy: integer('triggered_by').references(() => users.id) });
export const metrics = sqliteTable('metrics', { id: integer().primaryKey({ autoIncrement: true }), countryId: integer('country_id').references(() => countries.id), siteId: integer('site_id').references(() => sites.id), demandRegionId: integer('demand_region_id').references(() => demandRegions.id), metricName: text('metric_name').notNull().references(() => metricDefinitions.name), value: real(), unit: text().notNull().references(() => units.code), reportingPeriod: text('reporting_period'), claimType: text('claim_type').notNull().default('fact'), sourceId: integer('source_id').notNull().references(() => sources.id), refreshRunId: integer('refresh_run_id').references(() => refreshRuns.id), retrievedAt: text('retrieved_at').notNull(), confidence: text().notNull(), notes: text(), enteredBy: integer('entered_by').references(() => users.id) }, (t) => [index('idx_metrics_country').on(t.countryId, t.metricName, t.retrievedAt), index('idx_metrics_site').on(t.siteId, t.metricName, t.retrievedAt), index('idx_metrics_site_region').on(t.siteId, t.demandRegionId, t.metricName, t.retrievedAt)]);
export const designs = sqliteTable('designs', { id: integer().primaryKey({ autoIncrement: true }), teamId: integer('team_id').notNull().unique().references(() => teams.id), name: text().notNull(), selectedCountryId: integer('selected_country_id').references(() => countries.id), selectedSiteId: integer('selected_site_id').references(() => sites.id), designSummary: text('design_summary'), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull() });
export const designParameters = sqliteTable('design_parameters', { id: integer().primaryKey({ autoIncrement: true }), designId: integer('design_id').notNull().references(() => designs.id), name: text().notNull().references(() => parameterDefinitions.name), value: real().notNull(), claimType: text('claim_type').notNull(), rationale: text().notNull(), sourceId: integer('source_id').references(() => sources.id), createdAt: text('created_at').notNull(), createdBy: integer('created_by').references(() => users.id) }, (t) => [index('idx_params').on(t.designId, t.name, t.createdAt)]);
export const scenarios = sqliteTable('scenarios', { id: integer().primaryKey({ autoIncrement: true }), designId: integer('design_id').notNull().references(() => designs.id), name: text().notNull(), kind: text().notNull(), description: text().notNull(), createdAt: text('created_at').notNull() }, (t) => [uniqueIndex('scenarios_design_name').on(t.designId, t.name)]);
export const scenarioOverrides = sqliteTable('scenario_overrides', { id: integer().primaryKey({ autoIncrement: true }), scenarioId: integer('scenario_id').notNull().references(() => scenarios.id), parameterName: text('parameter_name').notNull().references(() => parameterDefinitions.name), value: real().notNull(), rationale: text().notNull(), createdAt: text('created_at').notNull(), createdBy: integer('created_by').references(() => users.id) }, (t) => [index('idx_overrides').on(t.scenarioId, t.parameterName, t.createdAt)]);
export const designClaims = sqliteTable('design_claims', { id: integer().primaryKey({ autoIncrement: true }), designId: integer('design_id').notNull().references(() => designs.id), claimText: text('claim_text').notNull(), claimType: text('claim_type').notNull(), value: real(), unit: text().references(() => units.code), calcKey: text('calc_key'), sourceId: integer('source_id').references(() => sources.id), status: text().notNull(), confidence: text(), topic: text().notNull(), supersedesClaimId: integer('supersedes_claim_id').references(() => designClaims.id), createdAt: text('created_at').notNull(), createdBy: integer('created_by').references(() => users.id) }, (t) => [index('idx_claims').on(t.designId, t.claimType, t.topic)]);
export const claimLinks = sqliteTable('claim_links', { id: integer().primaryKey({ autoIncrement: true }), claimId: integer('claim_id').notNull().references(() => designClaims.id), linkRole: text('link_role').notNull(), sourceId: integer('source_id').references(() => sources.id), inputClaimId: integer('input_claim_id').references(() => designClaims.id), metricId: integer('metric_id').references(() => metrics.id), parameterName: text('parameter_name').references(() => parameterDefinitions.name) }, (t) => [index('idx_links_claim').on(t.claimId)]);
