import Link from 'next/link';
import { annualEnergyGwh, facilityPowerMw, outageEnergyMwh, proposalData, weightedScore } from '../../lib/db/proposal';

export default function Evidence() {
  const d=proposalData.design;
  return <>
    <section className="page-head"><div className="shell"><span className="eyebrow">Decision basis</span><h1>Follow the working.</h1><p>Design inputs, calculations, judgment scores and open questions are separated so the basis of the recommendation remains legible.</p></div></section>
    <section className="section"><div className="shell"><div className="section-head"><div><span className="eyebrow">Calculated figures</span><h2>Formulas behind the headline.</h2></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Output</th><th>Result</th><th>Working</th><th>Type</th></tr></thead><tbody>
      <tr><td>Facility load</td><td><strong>{facilityPowerMw()} MW</strong></td><td>{d.itLoadMw} MW IT × {d.pue.toFixed(2)} PUE</td><td><span className="tag">Calculation</span></td></tr>
      <tr><td>Annual energy</td><td><strong>{annualEnergyGwh()} GWh</strong></td><td>{facilityPowerMw()} MW × {d.operatingHours.toLocaleString()} hours ÷ 1,000</td><td><span className="tag">Calculation</span></td></tr>
      <tr><td>Backup event energy</td><td><strong>{outageEnergyMwh().toLocaleString()} MWh</strong></td><td>{facilityPowerMw()} MW × {d.gridOutageHours} hours</td><td><span className="tag">Calculation</span></td></tr>
      {proposalData.candidates.map(c=><tr key={c.id}><td>{c.site} weighted score</td><td><strong>{weightedScore(c.scores).toFixed(2)}</strong></td><td>Sum of each criterion score × its weight</td><td><span className="tag">Calculation</span></td></tr>)}
    </tbody></table></div></div></section>
    <section className="section band"><div className="shell"><div className="section-head"><div><span className="eyebrow">Input ledger</span><h2>Assumptions and decisions.</h2></div></div><div className="grid-2"><div className="card"><h3>Design assumptions</h3><ul className="list"><li>IT demand: {d.itLoadMw} MW</li><li>Facility PUE: {d.pue.toFixed(2)}</li><li>Annual operating hours: {d.operatingHours.toLocaleString()}</li><li>Latency threshold: {d.latencyThresholdMs} ms round trip</li></ul></div><div className="card"><h3>Design decisions</h3><ul className="list"><li>Reference location: {d.location}</li><li>Cooling: {d.cooling}</li><li>Shared capacity across member institutions</li><li>Stage-gated investment path</li></ul></div></div></div></section>
    <section className="section"><div className="shell"><div className="section-head"><div><span className="eyebrow">Open questions</span><h2>What still determines approval.</h2></div></div><div className="grid-3"><div className="card"><span className="tag gray">Unknown</span><h3>Grid connection</h3><p>No site-specific energization date or connection cost is established for the three candidates.</p></div><div className="card"><span className="tag gray">Unknown</span><h3>Member commitment</h3><p>Contracted GPU-hours and each institution’s minimum reservation remain to be agreed.</p></div><div className="card"><span className="tag gray">Unknown</span><h3>Vendor pricing</h3><p>Equipment, construction, lease and service-level offers determine the bankable economics.</p></div></div><p className="lead" style={{marginTop:30}}>The <Link className="text-link" href="/countries">country comparison</Link> shows judgment scores; the <Link className="text-link" href="/investment">investment explorer</Link> applies editable scenario inputs. Neither replaces a utility offer or a contracted price.</p></div></section>
  </>;
}
