import { proposalData, weightedScore } from '../../lib/db/proposal';

export default function Countries() {
  const candidates = proposalData.candidates;
  return <>
    <section className="page-head"><div className="shell"><span className="eyebrow">Location strategy</span><h1>Three places. One decision.</h1><p>The same weighted criteria compare a Texas, Québec and Helsinki reference site. Scores are design judgments on a five-point scale.</p></div></section>
    <section className="section"><div className="shell"><div className="grid-3">{candidates.map((c,i)=><article className={i===0?'card accent':'card'} key={c.id}><span className="eyebrow">{i===0?'Selected reference':'Alternative'}</span><h3>{c.site}<br/><span className="subtle">{c.country}</span></h3><div className="number"><a href={'/evidence#score-'+c.id}>{weightedScore(c.scores).toFixed(2)}</a></div><div className="scorebar"><span style={{width:(weightedScore(c.scores)/5*100)+'%'}}/></div><p style={{marginTop:20}}>{c.demandShare}% of modeled addressable demand within {proposalData.design.latencyThresholdMs} ms round trip · calculation</p></article>)}</div></div></section>
    <section className="section tight"><div className="shell"><div className="section-head"><div><span className="eyebrow">Assessment</span><h2>Where the score comes from</h2></div><a className="text-link" href="/evidence">Method and evidence ↗</a></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Criterion</th><th>Weight</th>{candidates.map(c=><th key={c.id}>{c.site}</th>)}</tr></thead><tbody>{proposalData.criteria.map((criterion,index)=><tr key={criterion.id}><td><strong>{criterion.name}</strong><br/><span className="subtle">{criterion.id}</span></td><td>{criterion.weight}%</td>{candidates.map(c=><td key={c.id}>{criterion.weight===0?'Not established':c.scores[index]+' / 5'}</td>)}</tr>)}<tr><td><strong>Weighted total</strong></td><td>100%</td>{candidates.map(c=><td key={c.id}><strong>{weightedScore(c.scores).toFixed(2)}</strong></td>)}</tr></tbody></table></div><p className="subtle">Connection timing remains open for every candidate and carries no weight in this comparison until a utility provides a site-specific schedule.</p></div></section>
    <section className="section band"><div className="shell"><div className="section-head"><div><span className="eyebrow">What could change</span><h2>The choice stays conditional.</h2></div></div><div className="grid-2">{proposalData.reversalTriggers.map((x,i)=><div className="card" key={x}><span className="eyebrow">Trigger {i+1}</span><h3>{x}</h3></div>)}</div></div></section>
  </>;
}
